// AUTO-GENERATED by scripts/build-surahs.mjs — do not edit by hand.
// Canonical 114-surah table: n (number), name (English), ar (Arabic), ayahs (verse count).
// Source: references/surah.json.

export const SURAHS = [
  {
    "n": 1,
    "name": "Al-Fatiha",
    "ar": "الفاتحة",
    "ayahs": 7
  },
  {
    "n": 2,
    "name": "Al-Baqara",
    "ar": "البقرة",
    "ayahs": 286
  },
  {
    "n": 3,
    "name": "Aal-Imran",
    "ar": "آل عمران",
    "ayahs": 200
  },
  {
    "n": 4,
    "name": "An-Nisaa'",
    "ar": "النساء",
    "ayahs": 176
  },
  {
    "n": 5,
    "name": "Al-Ma'ida",
    "ar": "المائدة",
    "ayahs": 120
  },
  {
    "n": 6,
    "name": "Al-An'am",
    "ar": "الأنعام",
    "ayahs": 165
  },
  {
    "n": 7,
    "name": "Al-A'raf",
    "ar": "الأعراف",
    "ayahs": 206
  },
  {
    "n": 8,
    "name": "Al-Anfal",
    "ar": "الأنفال",
    "ayahs": 75
  },
  {
    "n": 9,
    "name": "Al-Tawba",
    "ar": "التوبة",
    "ayahs": 129
  },
  {
    "n": 10,
    "name": "Yunus",
    "ar": "يونس",
    "ayahs": 109
  },
  {
    "n": 11,
    "name": "Hud",
    "ar": "هود",
    "ayahs": 123
  },
  {
    "n": 12,
    "name": "Yusuf",
    "ar": "يوسف",
    "ayahs": 111
  },
  {
    "n": 13,
    "name": "Ar-Ra'd",
    "ar": "الرعد",
    "ayahs": 43
  },
  {
    "n": 14,
    "name": "Ibrahim",
    "ar": "إبراهيم",
    "ayahs": 52
  },
  {
    "n": 15,
    "name": "Al-Hijr",
    "ar": "الحجر",
    "ayahs": 99
  },
  {
    "n": 16,
    "name": "An-Nahl",
    "ar": "النحل",
    "ayahs": 128
  },
  {
    "n": 17,
    "name": "Al-Israa",
    "ar": "الإسراء",
    "ayahs": 111
  },
  {
    "n": 18,
    "name": "Al-Kahf",
    "ar": "الكهف",
    "ayahs": 110
  },
  {
    "n": 19,
    "name": "Maryam",
    "ar": "مريم",
    "ayahs": 98
  },
  {
    "n": 20,
    "name": "Ta-Ha",
    "ar": "طه",
    "ayahs": 135
  },
  {
    "n": 21,
    "name": "Al-Anbiya",
    "ar": "الأنبياء",
    "ayahs": 112
  },
  {
    "n": 22,
    "name": "Al-Hajj",
    "ar": "الحج",
    "ayahs": 78
  },
  {
    "n": 23,
    "name": "Al-Muminun",
    "ar": "المؤمنون",
    "ayahs": 118
  },
  {
    "n": 24,
    "name": "An-Nur",
    "ar": "النور",
    "ayahs": 64
  },
  {
    "n": 25,
    "name": "Al-Furqan",
    "ar": "الفرقان",
    "ayahs": 77
  },
  {
    "n": 26,
    "name": "Ash-Shuara",
    "ar": "الشعراء",
    "ayahs": 227
  },
  {
    "n": 27,
    "name": "An-Naml",
    "ar": "النمل",
    "ayahs": 93
  },
  {
    "n": 28,
    "name": "Al-Qasas",
    "ar": "القصص",
    "ayahs": 88
  },
  {
    "n": 29,
    "name": "Al-Ankabut",
    "ar": "العنكبوت",
    "ayahs": 69
  },
  {
    "n": 30,
    "name": "Ar-Rum",
    "ar": "الروم",
    "ayahs": 60
  },
  {
    "n": 31,
    "name": "Luqman",
    "ar": "لقمان",
    "ayahs": 34
  },
  {
    "n": 32,
    "name": "As-Sajdah",
    "ar": "السجدة",
    "ayahs": 30
  },
  {
    "n": 33,
    "name": "Al-Ahzab",
    "ar": "الأحزاب",
    "ayahs": 73
  },
  {
    "n": 34,
    "name": "Saba",
    "ar": "سبأ",
    "ayahs": 54
  },
  {
    "n": 35,
    "name": "Fatir",
    "ar": "فاطر",
    "ayahs": 45
  },
  {
    "n": 36,
    "name": "Yasin",
    "ar": "يس",
    "ayahs": 83
  },
  {
    "n": 37,
    "name": "As-Saffat",
    "ar": "الصافات",
    "ayahs": 182
  },
  {
    "n": 38,
    "name": "Sad",
    "ar": "ص",
    "ayahs": 88
  },
  {
    "n": 39,
    "name": "Az-Zumar",
    "ar": "الزمر",
    "ayahs": 75
  },
  {
    "n": 40,
    "name": "Ghafir",
    "ar": "غافر",
    "ayahs": 85
  },
  {
    "n": 41,
    "name": "Fussilat",
    "ar": "فصلت",
    "ayahs": 54
  },
  {
    "n": 42,
    "name": "Ash-Shura",
    "ar": "الشورى",
    "ayahs": 53
  },
  {
    "n": 43,
    "name": "Az-Zukhruf",
    "ar": "الزخرف",
    "ayahs": 89
  },
  {
    "n": 44,
    "name": "Ad-Dukhan",
    "ar": "الدخان",
    "ayahs": 59
  },
  {
    "n": 45,
    "name": "Al-Jathiya",
    "ar": "الجاثية",
    "ayahs": 37
  },
  {
    "n": 46,
    "name": "Al-Ahqaf",
    "ar": "الأحقاف",
    "ayahs": 35
  },
  {
    "n": 47,
    "name": "Muhammad",
    "ar": "محمد",
    "ayahs": 38
  },
  {
    "n": 48,
    "name": "Al-Fath",
    "ar": "الفتح",
    "ayahs": 29
  },
  {
    "n": 49,
    "name": "Al-Hujurat",
    "ar": "الحجرات",
    "ayahs": 18
  },
  {
    "n": 50,
    "name": "Qaf",
    "ar": "ق",
    "ayahs": 45
  },
  {
    "n": 51,
    "name": "Az-Zariyat",
    "ar": "الذاريات",
    "ayahs": 60
  },
  {
    "n": 52,
    "name": "At-Tur",
    "ar": "الطور",
    "ayahs": 49
  },
  {
    "n": 53,
    "name": "An-Najm",
    "ar": "النجم",
    "ayahs": 62
  },
  {
    "n": 54,
    "name": "Al-Qamar",
    "ar": "القمر",
    "ayahs": 55
  },
  {
    "n": 55,
    "name": "Ar-Rahman",
    "ar": "الرحمن",
    "ayahs": 78
  },
  {
    "n": 56,
    "name": "Al-Waqia",
    "ar": "الواقعة",
    "ayahs": 96
  },
  {
    "n": 57,
    "name": "Al-Hadid",
    "ar": "الحديد",
    "ayahs": 29
  },
  {
    "n": 58,
    "name": "Al-Mujadilah",
    "ar": "المجادلة",
    "ayahs": 22
  },
  {
    "n": 59,
    "name": "Al-Hashr",
    "ar": "الحشر",
    "ayahs": 24
  },
  {
    "n": 60,
    "name": "Al-Mumtahinah",
    "ar": "الممتحنة",
    "ayahs": 13
  },
  {
    "n": 61,
    "name": "As-Saff",
    "ar": "الصف",
    "ayahs": 14
  },
  {
    "n": 62,
    "name": "Al-Jumu'ah",
    "ar": "الجمعة",
    "ayahs": 11
  },
  {
    "n": 63,
    "name": "Al-Munafiqun",
    "ar": "المنافقون",
    "ayahs": 11
  },
  {
    "n": 64,
    "name": "At-Taghabun",
    "ar": "التغابن",
    "ayahs": 18
  },
  {
    "n": 65,
    "name": "At-Talaq",
    "ar": "الطلاق",
    "ayahs": 12
  },
  {
    "n": 66,
    "name": "At-Tahrim",
    "ar": "التحريم",
    "ayahs": 12
  },
  {
    "n": 67,
    "name": "Al-Mulk",
    "ar": "الملك",
    "ayahs": 30
  },
  {
    "n": 68,
    "name": "Al-Qalam",
    "ar": "القلم",
    "ayahs": 52
  },
  {
    "n": 69,
    "name": "Al-Haqqah",
    "ar": "الحاقة",
    "ayahs": 52
  },
  {
    "n": 70,
    "name": "Al-Ma'arij",
    "ar": "المعارج",
    "ayahs": 44
  },
  {
    "n": 71,
    "name": "Nuh",
    "ar": "نوح",
    "ayahs": 28
  },
  {
    "n": 72,
    "name": "Al-Jinn",
    "ar": "الجن",
    "ayahs": 28
  },
  {
    "n": 73,
    "name": "Al-Muzzammil",
    "ar": "المزمل",
    "ayahs": 20
  },
  {
    "n": 74,
    "name": "Al-Muddaththir",
    "ar": "المدثر",
    "ayahs": 56
  },
  {
    "n": 75,
    "name": "Al-Qiyamah",
    "ar": "القيامة",
    "ayahs": 40
  },
  {
    "n": 76,
    "name": "Al-Insan",
    "ar": "الإنسان",
    "ayahs": 31
  },
  {
    "n": 77,
    "name": "Al-Mursalat",
    "ar": "المرسلات",
    "ayahs": 50
  },
  {
    "n": 78,
    "name": "An-Naba",
    "ar": "النبأ",
    "ayahs": 40
  },
  {
    "n": 79,
    "name": "An-Naziat",
    "ar": "النازعات",
    "ayahs": 46
  },
  {
    "n": 80,
    "name": "Abasa",
    "ar": "عبس",
    "ayahs": 42
  },
  {
    "n": 81,
    "name": "At-Takwir",
    "ar": "التكوير",
    "ayahs": 29
  },
  {
    "n": 82,
    "name": "Al-Infitar",
    "ar": "الإنفطار",
    "ayahs": 19
  },
  {
    "n": 83,
    "name": "Al-Mutaffifin",
    "ar": "المطففين",
    "ayahs": 36
  },
  {
    "n": 84,
    "name": "Al-Inshiqaq",
    "ar": "الإنشقاق",
    "ayahs": 25
  },
  {
    "n": 85,
    "name": "Al-Buruj",
    "ar": "البروج",
    "ayahs": 22
  },
  {
    "n": 86,
    "name": "At-Tariq",
    "ar": "الطارق",
    "ayahs": 17
  },
  {
    "n": 87,
    "name": "Al-Ala",
    "ar": "الأعلى",
    "ayahs": 19
  },
  {
    "n": 88,
    "name": "Al-Ghashiyah",
    "ar": "الغاشية",
    "ayahs": 26
  },
  {
    "n": 89,
    "name": "Al-Fajr",
    "ar": "الفجر",
    "ayahs": 30
  },
  {
    "n": 90,
    "name": "Al-Balad",
    "ar": "البلد",
    "ayahs": 20
  },
  {
    "n": 91,
    "name": "Ash-Shams",
    "ar": "الشمس",
    "ayahs": 15
  },
  {
    "n": 92,
    "name": "Al-Lail",
    "ar": "الليل",
    "ayahs": 21
  },
  {
    "n": 93,
    "name": "Ad-Duha",
    "ar": "الضحى",
    "ayahs": 11
  },
  {
    "n": 94,
    "name": "Ash-Sharh",
    "ar": "الشرح",
    "ayahs": 8
  },
  {
    "n": 95,
    "name": "At-Tin",
    "ar": "التين",
    "ayahs": 8
  },
  {
    "n": 96,
    "name": "Al-Alaq",
    "ar": "العلق",
    "ayahs": 19
  },
  {
    "n": 97,
    "name": "Al-Qadr",
    "ar": "القدر",
    "ayahs": 5
  },
  {
    "n": 98,
    "name": "Al-Bayinah",
    "ar": "البينة",
    "ayahs": 8
  },
  {
    "n": 99,
    "name": "Az-Zalzalah",
    "ar": "الزلزلة",
    "ayahs": 8
  },
  {
    "n": 100,
    "name": "Al-Adiyat",
    "ar": "العاديات",
    "ayahs": 11
  },
  {
    "n": 101,
    "name": "Al-Qariah",
    "ar": "القارعة",
    "ayahs": 11
  },
  {
    "n": 102,
    "name": "Al-Takathur",
    "ar": "التكاثر",
    "ayahs": 8
  },
  {
    "n": 103,
    "name": "Al-Asr",
    "ar": "العصر",
    "ayahs": 3
  },
  {
    "n": 104,
    "name": "Al-Humazah",
    "ar": "الهمزة",
    "ayahs": 9
  },
  {
    "n": 105,
    "name": "Al-Fil",
    "ar": "الفيل",
    "ayahs": 5
  },
  {
    "n": 106,
    "name": "Quraish",
    "ar": "قريش",
    "ayahs": 4
  },
  {
    "n": 107,
    "name": "Al-Ma'un",
    "ar": "الماعون",
    "ayahs": 7
  },
  {
    "n": 108,
    "name": "Al-Kauthar",
    "ar": "الكوثر",
    "ayahs": 3
  },
  {
    "n": 109,
    "name": "Al-Kafirun",
    "ar": "الكافرون",
    "ayahs": 6
  },
  {
    "n": 110,
    "name": "An-Nasr",
    "ar": "النصر",
    "ayahs": 3
  },
  {
    "n": 111,
    "name": "Al-Masad",
    "ar": "المسد",
    "ayahs": 5
  },
  {
    "n": 112,
    "name": "Al-Ikhlas",
    "ar": "الإخلاص",
    "ayahs": 4
  },
  {
    "n": 113,
    "name": "Al-Falaq",
    "ar": "الفلق",
    "ayahs": 5
  },
  {
    "n": 114,
    "name": "An-Nas",
    "ar": "الناس",
    "ayahs": 6
  }
];

// Lookup by surah number (1-114).
export const SURAH_BY_N = Object.fromEntries(SURAHS.map((s) => [s.n, s]));
