// Dev-only build step. Reads the reference surah table (references/surah.json —
// an untracked dev asset in the main working tree) and emits a compact,
// browser-safe lib/surahs.js used by the admin surah picker and slug parsing.
//
// Usage: node scripts/build-surahs.mjs [path/to/surah.json]
// Default source path resolves to ../references/surah.json relative to repo root.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const srcArg = process.argv[2];
// Prefer an explicit arg; else look in this repo, then the parent (main) tree
// since surah.json is an untracked dev asset that may only exist in the main checkout.
const candidates = [
  srcArg,
  join(repoRoot, "references", "surah.json"),
  resolve(repoRoot, "..", "..", "..", "references", "surah.json"),
].filter(Boolean);

let raw, usedPath;
for (const p of candidates) {
  try {
    raw = readFileSync(p, "utf8");
    usedPath = p;
    break;
  } catch {
    /* try next */
  }
}
if (!raw) {
  console.error("surah.json not found. Tried:\n" + candidates.join("\n"));
  process.exit(1);
}

const data = JSON.parse(raw);
const surahs = data.map((s) => ({
  n: Number(s.index),
  name: s.title,
  ar: s.titleAr,
  ayahs: s.count,
}));

if (surahs.length !== 114) {
  console.error(`Expected 114 surahs, got ${surahs.length}. Aborting.`);
  process.exit(1);
}

const body = `// AUTO-GENERATED by scripts/build-surahs.mjs — do not edit by hand.
// Canonical 114-surah table: n (number), name (English), ar (Arabic), ayahs (verse count).
// Source: references/surah.json.

export const SURAHS = ${JSON.stringify(surahs, null, 2)};

// Lookup by surah number (1-114).
export const SURAH_BY_N = Object.fromEntries(SURAHS.map((s) => [s.n, s]));
`;

const out = join(repoRoot, "lib", "surahs.js");
writeFileSync(out, body);
console.log(`Wrote ${out} (${surahs.length} surahs) from ${usedPath}`);
